blank_issues_enabled: false
contact_links:
  - name: General questions / discussion
    url: https://github.com/orgs/Mr-Rainbowsmoke/discussions
    about: Use Discussions for questions, ideas, and brainstorming.
